version: "3"

services:
  mysql_db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    volumes:
      - /var/lib/docker/volumes/currency-converter-db/_data:/var/lib/mysql

  currency-converter:
    image: sofienechihi/my-public-repo:currency-converter
    restart: on-failure
    depends_on:
      - mysql_db
    environment:
      - HOST=mysql_db
      - MYSQLDB_LOCAL_PORT=${MYSQLDB_LOCAL_PORT}
      - MYSQLDB_USER=${MYSQLDB_USER}
      - MYSQLDB_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    ports:
      - ${NEST_LOCAL_PORT}:${NEST_DOCKER_PORT}